#--------------------------------------------------------------------------------------------------
# Global Settings
#--------------------------------------------------------------------------------------------------

# The number of tasks in a Lockout challenge
taskCount: 27

# The number of seconds players are frozen before starting a game
queueTime: 5

# The number of seconds to countdown for a game before sudden death
timeLimit: 60

#--------------------------------------------------------------------------------------------------
# Task-Specific Settings
#--------------------------------------------------------------------------------------------------

# Task: Eat an Item. List of possible items you can eat
eatAnItemItems:
- COOKIE
- GOLDEN_CARROT
- GOLDEN_APPLE
- MELON_SLICE
- GLOW_BERRIES
- DRIED_KELP
- POISONOUS_POTATO
- PUFFERFISH
- PUMPKIN_PIE
- RABBIT_STEW
- HONEY_BOTTLE

# Task: Ride an entity. List of possible EntityTypes to ride
rideAnEntityMounts:
- CAMEL
- DONKEY
- HORSE
- PIG
- MULE
- STRIDER
- MINECART

# Task: Punch an entity with item. Possible entities to punch
punchAnEntityEntityTypes:
- ARMADILLO
- AXOLOTL
- BAT
- BEE
- CAMEL
- DOLPHIN
- DONKEY
- DROWNED
- ENDERMAN
- GLOW_SQUID
- GOAT
- HUSK
- IRON_GOLEM
- LLAMA
- OCELOT
- PARROT
- PIGLIN
- POLAR_BEAR
- PUFFERFISH
- SNOW_GOLEM
- STRAY
- TURTLE
- VILLAGER
- WITCH
- WOLF

# Task: Punch an entity with item. Possible items to punch with
punchAnEntityItemTypes:
- APPLE
- BEETROOT
- COD
- COOKIE
- GLOW_BERRIES
- PUFFERFISH
- SALMON
- SWEET_BERRIES
- TROPICAL_FISH

# Task: Place an item in an item frame. Possible items to place in the frame
placeItemInItemFrameItemTypes:
- AMETHYST_SHARD
- COAL
- COPPER_INGOT
- DIAMOND
- EMERALD
- GOLD_INGOT
- IRON_INGOT
- LAPIS_LAZULI
- QUARTZ

# Task: Break an item. Possible items to break, and how many to break
breakItemsTask:
  ACACIA_LOG: 10
  ANDESITE: 32
  BIRCH_LOG: 10
  BLACKSTONE: 1
  BLUE_ICE: 1
  BOOKSHELF: 5
  BONE_BLOCK: 1
  BRICKS: 5
  CHISELED_STONE_BRICKS: 1
  CLAY: 10
  COAL_ORE: 10
  COBBLESTONE: 128
  COBWEB: 1
  CRIMSON_NYLIUM: 1
  DIAMOND_ORE: 1
  DIRT: 128
  DARK_OAK_LOG: 10
  EMERALD_ORE: 1
  GLOWSTONE: 5
  GOLD_ORE: 2
  GRASS_BLOCK: 128
  GRAVEL: 64
  HAY_BLOCK: 10
  ICE: 10
  IRON_ORE: 1
  JUNGLE_LOG: 10
  LAPIS_ORE: 1
  LIGHT_GRAY_STAINED_GLASS: 1
  MELON: 3
  SPAWNER: 1
  MOSSY_COBBLESTONE: 1
  NETHERRACK: 64
  OAK_PLANKS: 64
  OBSIDIAN: 1
  PRISMARINE: 1
  RED_SANDSTONE: 32
  SAND: 64
  SEA_LANTERN: 1
  SLIME_BLOCK: 1
  SNOW_BLOCK: 64
  STONE: 64
  TNT: 1
  WHITE_CONCRETE: 1
  YELLOW_TERRACOTTA: 1

# Task: Obtain an item. Possible items to obtain
obtainAnItemItemTypes:
  OAK_LEAVES: 1
  BIRCH_LEAVES: 1
  DARK_OAK_LEAVES: 1
  AZALEA_LEAVES: 1
  SPRUCE_SAPLING: 1
  ACACIA_SAPLING: 1
  CHERRY_SAPLING: 1
  SALMON_BUCKET: 1
  TROPICAL_FISH_BUCKET: 1
  PUFFERFISH_BUCKET: 1
  AXOLOTL_BUCKET: 1
  LAVA_BUCKET: 1
  MILK_BUCKET: 1
  CLOCK: 1
  CARROT_ON_A_STICK: 1
  MANGROVE_BOAT: 1
  CHERRY_BOAT: 1
  POWERED_RAIL: 1
  DETECTOR_RAIL: 1
  ACTIVATOR_RAIL: 1
  GOAT_HORN: 1
  SADDLE: 1
  FIREWORK_ROCKET: 1
  SNOWBALL: 1
  HEART_OF_THE_SEA: 1
  RABBIT_HIDE: 1
  DIAMOND: 1
  FEATHER: 1
  GLOW_INK_SAC: 1
  NAUTILUS_SHELL: 1
  CHAIN: 1
  LANTERN: 1
  REDSTONE_TORCH: 1
  BELL: 1
  CAULDRON: 1
  BREWING_STAND: 1
  OAK_HANGING_SIGN: 1
  BIRCH_HANGING_SIGN: 1
  ACACIA_HANGING_SIGN: 1
  WARPED_HANGING_SIGN: 1
  BARREL: 1
  WHITE_BED: 1
  BLACK_BED: 1
  LIME_BED: 1
  LIGHT_BLUE_BED: 1
  WHITE_CANDLE: 1
  MAGENTA_CANDLE: 1
  PINK_CANDLE: 1
  WHITE_BANNER: 1
  BLACK_BANNER: 1
  RED_BANNER: 1
  YELLOW_BANNER: 1
  BLUE_BANNER: 1
  COBBLESTONE: 5
  COAL: 64
  DIRT: 320
  SAND: 128
  CRYING_OBSIDIAN: 1
  SEA_PICKLE: 10
  TURTLE_SCUTE: 1
  REDSTONE_TORCH: 64
  GHAST_TEAR: 1
  NETHERRACK: 640
  PINK_WOOL: 10
  APPLE: 5
  BAKED_POTATO: 1
  MELON_SLICE: 64
  NETHER_WART: 1
  RABBIT_FOOT: 1
  SLIME_BLOCK: 1
  SPONGE: 1


# Task: Place an item. Possible items to place, and the amount to place
placeAnItemItemTypes:
  CRIMSON_FUNGUS: 1
  WARPED_FUNGUS: 1
  GLOWSTONE: 1
  JACK_O_LANTERN: 1
  REDSTONE_BLOCK: 1
  GOLD_BLOCK: 1
  COMPARATOR: 1
  DRIED_KELP_BLOCK: 1
  FERN: 1
  HONEYCOMB_BLOCK: 1
  HOPPER: 1
  LANTERN: 1
  LIGHT_GRAY_GLAZED_TERRACOTTA: 1
  WHITE_BANNER: 1
  NETHER_BRICKS: 1
  OBSERVER: 1
  POLISHED_ANDESITE_STAIRS:
  QUARTZ_PILLAR: 1
  RED_GLAZED_TERRACOTTA: 1
  RED_SANDSTONE_SLAB:
  REDSTONE_LAMP: 1
  WARPED_FENCE_GATE: 1
  WHITE_CARPET: 5
  COBBLESTONE_WALL: 1
  STONE_BRICK_WALL: 1
  GRANITE_WALL: 1
  DIORITE_WALL: 1
  ANDESITE_WALL: 1
  COBBLED_DEEPSLATE_WALL: 1
  TUFF_WALL: 1
  BRICK_WALL: 1
  SANDSTONE_WALL: 1
  BLACKSTONE_WALL: 1
  BONE_BLOCK: 1
  CRIMSON_FUNGUS: 1
  WARPED_FUNGUS: 1
  WHITE_STAINED_GLASS: 1
  BLACK_STAINED_GLASS: 1
  RED_STAINED_GLASS: 1
  YELLOW_STAINED_GLASS: 1
  BLUE_STAINED_GLASS: 1