#--------------------------------------------------------------------------------------------------
# Global Settings
#--------------------------------------------------------------------------------------------------

# The number of tasks in a Lockout challenge
taskCount: 25

# The number of seconds players are frozen before starting a game
queueTime: 5

# The number of seconds to countdown for a game before sudden death
timeLimit: 60

#--------------------------------------------------------------------------------------------------
# Task-Specific Settings
#--------------------------------------------------------------------------------------------------

# Task: Eat an Item. List of possible items you can eat
eatAnItemItems:
- COOKIE
- GOLDEN_CARROT
- GOLDEN_APPLE
- MELON_SLICE
- GLOW_BERRIES
- DRIED_KELP
- POISONOUS_POTATO
- PUFFERFISH
- PUMPKIN_PIE
- RABBIT_STEW
- HONEY_BOTTLE

# Task: Ride an animal. List of possible animals to ride
rideAnAnimalMounts:
- CAMEL
- DONKEY
- HORSE
- PIG
- MULE
- STRIDER