#--------------------------------------------------------------------------------------------------
# Global Settings
#--------------------------------------------------------------------------------------------------

# The number of tasks in a Lockout challenge
taskCount: 25

#--------------------------------------------------------------------------------------------------
# Task-Specific Settings
#--------------------------------------------------------------------------------------------------

# Task: Eat an Item. List of possible items you can eat
eatAnItemItems:
- COOKIE
- GOLDEN_CARROT