#--------------------------------------------------------------------------------------------------
# Global Settings
#--------------------------------------------------------------------------------------------------

# The number of tasks in a Lockout challenge
taskCount: 25

# The number of seconds players are frozen before starting a game
queueTime: 5

# The number of seconds to countdown for a game before sudden death
timeLimit: 60

#--------------------------------------------------------------------------------------------------
# Task-Specific Settings
#--------------------------------------------------------------------------------------------------

# Task: Eat an Item. List of possible items you can eat
eatAnItemItems:
- COOKIE
- GOLDEN_CARROT
- GOLDEN_APPLE
- MELON_SLICE
- GLOW_BERRIES
- DRIED_KELP
- POISONOUS_POTATO
- PUFFERFISH
- PUMPKIN_PIE
- RABBIT_STEW
- HONEY_BOTTLE

# Task: Ride an entity. List of possible EntityTypes to ride
rideAnEntityMounts:
- CAMEL
- DONKEY
- HORSE
- PIG
- MULE
- STRIDER
- MINECART

# Task: Punch an entity with item. Possible entities to punch
punchAnEntityEntityTypes:
- ARMADILLO
- AXOLOTL
- BAT
- BEE
- CAMEL
- DOLPHIN
- DONKEY
- DROWNED
- ENDERMAN
- GLOW_SQUID
- GOAT
- HUSK
- IRON_GOLEM
- LLAMA
- OCELOT
- PARROT
- PIGLIN
- POLAR_BEAR
- PUFFERFISH
- SNOW_GOLEM
- STRAY
- TURTLE
- VILLAGER
- WITCH
- WOLF

# Task: Punch an entity with item. Possible items to punch with
punchAnEntityItemTypes:
- APPLE
- BEETROOT
- COD
- COOKIE
- GLOW_BERRIES
- PUFFERFISH
- SALMON
- SWEET_BERRIES
- TROPICAL_FISH

# Task: Place an item in an item frame. Possible items to place in the frame
placeItemInItemFrameItemTypes:
- AMETHYST_SHARD
- COAL
- COPPER_INGOT
- DIAMOND
- EMERALD
- GOLD_INGOT
- IRON_INGOT
- LAPIS_LAZULI
- QUARTZ

# Task: Obtain an item. Possible items to obtain
obtainAnItemItemTypes:
- OAK_LEAVES
- SPRUCE_LEAVES
- BIRCH_LEAVES
- JUNGLE_LEAVES
- ACACIA_LEAVES
- DARK_OAK_LEAVES
- MANGROVE_LEAVES
- CHERRY_LEAVES
- AZALEA_LEAVES
- FLOWERING_AZALEA_LEAVES
- OAK_SAPLING
- SPRUCE_SAPLING
- BIRCH_SAPLING
- JUNGLE_SAPLING
- ACACIA_SAPLING
- DARK_OAK_SAPLING
- CHERRY_SAPLING
- SALMON_BUCKET
- TROPICAL_FISH_BUCKET
- PUFFERFISH_BUCKET
- AXOLOTL_BUCKET
- LAVA_BUCKET
- MILK_BUCKET
- CLOCK
- CARROT_ON_A_STICK
- MANGROVE_BOAT
- CHERRY_BOAT
- POWERED_RAIL
- DETECTOR_RAIL
- ACTIVATOR_RAIL
- GOAT_HORN
- SADDLE
- FIREWORK
- SNOWBALL
- HEART_OF_THE_SEA
- RABBIT_HIDE
- DIAMOND
- FEATHER
- GLOW_INK_SAC
- NAUTILUS_SHELL
- CHAIN
- LANTERN
- REDSTONE_TORCH
- BELL
- CAULDRON
- BREWING_STAND
- OAK_HANGING_SIGN
- SPRUCE_HANGING_SIGN
- BIRCH_HANGING_SIGN
- JUNGLE_HANGING_SIGN
- ACACIA_HANGING_SIGN
- DARK_OAK_HANGING_SIGN
- MANGROVE_HANGING_SIGN
- CHERRY_HANGING_SIGN
- BAMBOO_HANGING_SIGN
- WARPED_HANGING_SIGN
- BARREL
- WHITE_BED
- LIGHT_GRAY_BED
- GRAY_BED
- BLACK_BED
- BROWN_BED
- RED_BED
- ORANGE_BED
- YELLOW_BED
- LIME_BED
- GREEN_BED
- CYAN_BED
- LIGHT_BLUE_BED
- BLUE_BED
- PURPLE_BED
- MAGENTA_BED
- PINK_BED
- CANDLE
- WHITE_CANDLE
- LIGHT_GRAY_CANDLE
- GRAY_CANDLE
- BLACK_CANDLE
- BROWN_CANDLE
- RED_CANDLE
- ORANGE_CANDLE
- YELLOW_CANDLE
- LIME_CANDLE
- GREEN_CANDLE
- CYAN_CANDLE
- LIGHT_BLUE_CANDLE
- BLUE_CANDLE
- PURPLE_CANDLE
- MAGENTA_CANDLE
- PINK_CANDLE
- WHITE_BANNER
#- LIGHT_GRAY_BANNER
#- GRAY_BANNER
- BLACK_BANNER
#- BROWN_BANNER
- RED_BANNER
#- ORANGE_BANNER
- YELLOW_BANNER
#- LIME_BANNER
#- GREEN_BANNER
#- CYAN_BANNER
#- LIGHT_BLUE_BANNER
- BLUE_BANNER
#- PURPLE_BANNER
#- MAGNETA_BANNER
#- PINK_BANNER

# Task: Place an item. Possible items to place
placeAnItemItemTypes:
- COBBLESTONE_WALL
- STONE_BRICK_WALL
- GRANITE_WALL
- DIORITE_WALL
- ANDESITE_WALL
- COBBLED_DEEPSLATE_WALL
- TUFF_WALL
- BRICK_WALL
- SANDSTONE_WALL
- BLACKSTONE_WALL
- BONE_BLOCK
- CRIMSON_FUNGUS
- WARPED_FUNGUS
- WHITE_STAINED_GLASS
#- LIGHT_GRAY_STAINED_GLASS
#- GRAY_STAINED_GLASS
- BLACK_STAINED_GLASS
#- BROWN_STAINED_GLASS
- RED_STAINED_GLASS
#- ORANGE_STAINED_GLASS
- YELLOW_STAINED_GLASS
#- LIME_STAINED_GLASS
#- GREEN_STAINED_GLASS
#- CYAN_STAINED_GLASS
#- LIGHT_BLUE_STAINED_GLASS
- BLUE_STAINED_GLASS
#- PURPLE_STAINED_GLASS
#- MAGNETA_STAINED_GLASS
#- PINK_STAINED_GLASS
- WHITE_STAINED_GLASS_PANE
#- LIGHT_GRAY_STAINED_GLASS_PANE
#- GRAY_STAINED_GLASS_PANE
- BLACK_STAINED_GLASS_PANE
#- BROWN_STAINED_GLASS_PANE
- RED_STAINED_GLASS_PANE
#- ORANGE_STAINED_GLASS_PANE
- YELLOW_STAINED_GLASS_PANE
#- LIME_STAINED_GLASS_PANE
#- GREEN_STAINED_GLASS_PANE
#- CYAN_STAINED_GLASS_PANE
#- LIGHT_BLUE_STAINED_GLASS_PANE
- BLUE_STAINED_GLASS_PANE
#- PURPLE_STAINED_GLASS_PANE
#- MAGNETA_STAINED_GLASS_PANE
#- PINK_STAINED_GLASS_PANE